export interface Language {
  code: string;
  name: string;
  native: string;
  rtl?: boolean;
  flag: string;
  accent: string;
}

export const languages: Language[] = [
  {
    code: "af",
    name: "Afrikaans",
    native: "Afrikaans",
    flag: "🇿🇦",
    accent: "af-ZA-female-1",
  },
  {
    code: "am",
    name: "Amharic",
    native: "አማርኛ",
    flag: "🇪🇹",
    accent: "am-ET-female-1",
  },
  {
    code: "ar",
    name: "Arabic",
    native: "العربية",
    rtl: true,
    flag: "🇸🇦",
    accent: "ar-SA-female-1",
  },
  {
    code: "as",
    name: "Assamese",
    native: "অসমীয়া",
    flag: "🇮🇳",
    accent: "as-IN-female-1",
  },
  {
    code: "az",
    name: "Azerbaijani",
    native: "Azərbaycanca / آذربايجان",
    flag: "🇦🇿",
    accent: "az-AZ-female-1",
  },
  {
    code: "bg",
    name: "Bulgarian",
    native: "Български",
    flag: "🇧🇬",
    accent: "bg-BG-female-1",
  },
  {
    code: "bn",
    name: "Bengali",
    native: "বাংলা",
    flag: "🇧🇩",
    accent: "bn-BD-female-1",
  },
  {
    code: "bs",
    name: "Bosnian",
    native: "Bosanski",
    flag: "🇧🇦",
    accent: "bs-BA-female-1",
  },
  {
    code: "ca",
    name: "Catalan",
    native: "Català",
    flag: "🇪🇸",
    accent: "ca-ES-female-1",
  },
  {
    code: "cs",
    name: "Czech",
    native: "Česky",
    flag: "🇨🇿",
    accent: "cs-CZ-female-1",
  },
  {
    code: "cy",
    name: "Welsh",
    native: "Cymraeg",
    flag: "🇬🇧",
    accent: "cy-GB-female-1",
  },
  {
    code: "da",
    name: "Danish",
    native: "Dansk",
    flag: "🇩🇰",
    accent: "da-DK-female-1",
  },
  {
    code: "de",
    name: "German",
    native: "Deutsch",
    flag: "🇩🇪",
    accent: "de-DE-female-1",
  },
  {
    code: "el",
    name: "Greek",
    native: "Ελληνικά",
    flag: "🇬🇷",
    accent: "el-GR-female-2",
  },
  {
    code: "en",
    name: "English",
    native: "English",
    flag: "🇺🇸",
    accent: "en-US-female-3",
  },
  {
    code: "es",
    name: "Spanish",
    native: "Español",
    flag: "🇪🇸",
    accent: "es-ES-female-9",
  },
  {
    code: "et",
    name: "Estonian",
    native: "Eesti",
    flag: "🇪🇪",
    accent: "et-EE-female-11",
  },
  {
    code: "eu",
    name: "Basque",
    native: "Euskara",
    flag: "🇪🇸",
    accent: "eu-ES-female-11",
  },
  {
    code: "fa",
    name: "Persian",
    native: "فارسی",
    rtl: true,
    flag: "🇮🇷",
    accent: "fa-IR-female-11",
  },
  {
    code: "fi",
    name: "Finnish",
    native: "Suomi",
    flag: "🇫🇮",
    accent: "fi-FI-female-12",
  },
  {
    code: "fil",
    name: "Filipino",
    native: "Filipino",
    flag: "🇵🇭",
    accent: "fil-PH-female-11",
  },
  {
    code: "fr",
    name: "French",
    native: "Français",
    flag: "🇫🇷",
    accent: "fr-FR-female-12",
  },
  {
    code: "ga",
    name: "Irish",
    native: "Gaeilge",
    flag: "🇮🇪",
    accent: "ga-IE-female-12",
  },
  {
    code: "gl",
    name: "Galician",
    native: "Galego",
    flag: "🇪🇸",
    accent: "gl-ES-female-12",
  },
  {
    code: "gu",
    name: "Gujarati",
    native: "ગુજરાતી",
    flag: "🇮🇳",
    accent: "gu-IN-female-1",
  },
  {
    code: "he",
    name: "Hebrew",
    native: "עברית",
    rtl: true,
    flag: "🇮🇱",
    accent: "he-IL-female-12",
  },
  {
    code: "hi",
    name: "Hindi",
    native: "हिन्दी",
    flag: "🇮🇳",
    accent: "hi-IN-female-13",
  },
  {
    code: "hr",
    name: "Croatian",
    native: "Hrvatski",
    flag: "🇭🇷",
    accent: "hr-HR-female-12",
  },
  {
    code: "hu",
    name: "Hungarian",
    native: "Magyar",
    flag: "🇭🇺",
    accent: "hu-HU-female-13",
  },
  {
    code: "hy",
    name: "Armenian",
    native: "Հայերեն",
    flag: "🇦🇲",
    accent: "hy-AM-female-12",
  },
  {
    code: "id",
    name: "Indonesian",
    native: "Bahasa Indonesia",
    flag: "🇮🇩",
    accent: "id-ID-female-13",
  },
  {
    code: "is",
    name: "Icelandic",
    native: "Íslenska",
    flag: "🇮🇸",
    accent: "is-IS-female-12",
  },
  {
    code: "it",
    name: "Italian",
    native: "Italiano",
    flag: "🇮🇹",
    accent: "it-IT-female-13",
  },
  {
    code: "iu",
    name: "Inuktitut",
    native: "ᐃᓄᒃᑎᑐᑦ",
    flag: "🇨🇦",
    accent: "iu-Cans-CA-female-1",
  },
  {
    code: "ja",
    name: "Japanese",
    native: "日本語",
    flag: "🇯🇵",
    accent: "ja-JP-female-14",
  },
  {
    code: "jv",
    name: "Javanese",
    native: "Basa Jawa",
    flag: "🇮🇩",
    accent: "jv-ID-female-13",
  },
  {
    code: "ka",
    name: "Georgian",
    native: "ქართული",
    flag: "🇬🇪",
    accent: "ka-GE-female-13",
  },
  {
    code: "kk",
    name: "Kazakh",
    native: "Қазақша",
    flag: "🇰🇿",
    accent: "kk-KZ-female-13",
  },
  {
    code: "km",
    name: "Cambodian",
    native: "ភាសាខ្មែរ",
    flag: "🇰🇭",
    accent: "km-KH-female-13",
  },
  {
    code: "kn",
    name: "Kannada",
    native: "ಕನ್ನಡ",
    flag: "🇮🇳",
    accent: "kn-IN-female-13",
  },
  {
    code: "ko",
    name: "Korean",
    native: "한국어",
    flag: "🇰🇷",
    accent: "ko-KR-female-14",
  },
  {
    code: "lo",
    name: "Laotian",
    native: "ລາວ / Pha xa lao",
    flag: "🇱🇦",
    accent: "lo-LA-female-13",
  },
  {
    code: "lt",
    name: "Lithuanian",
    native: "Lietuvių",
    flag: "🇱🇹",
    accent: "lt-LT-female-13",
  },
  {
    code: "lv",
    name: "Latvian",
    native: "Latviešu",
    flag: "🇱🇻",
    accent: "lv-LV-female-13",
  },
  {
    code: "mk",
    name: "Macedonian",
    native: "Македонски",
    flag: "🇲🇰",
    accent: "mk-MK-female-13",
  },
  {
    code: "ml",
    name: "Malayalam",
    native: "മലയാളം",
    flag: "🇮🇳",
    accent: "ml-IN-female-13",
  },
  {
    code: "mn",
    name: "Mongolian",
    native: "Монгол",
    flag: "🇲🇳",
    accent: "mn-MN-female-13",
  },
  {
    code: "mr",
    name: "Marathi",
    native: "मराठी",
    flag: "🇮🇳",
    accent: "mr-IN-female-1",
  },
  {
    code: "ms",
    name: "Malay",
    native: "Bahasa Melayu",
    flag: "🇲🇾",
    accent: "ms-MY-female-13",
  },
  {
    code: "mt",
    name: "Maltese",
    native: "bil-Malti",
    flag: "🇲🇹",
    accent: "mt-MT-female-13",
  },
  {
    code: "my",
    name: "Burmese",
    native: "မြန်မာစာ",
    flag: "🇲🇲",
    accent: "my-MM-female-13",
  },
  {
    code: "nb",
    name: "Norwegian Bokmål",
    native: "Norsk bokmål",
    flag: "🇳🇴",
    accent: "nb-NO-female-14",
  },
  {
    code: "ne",
    name: "Nepali",
    native: "नेपाली",
    flag: "🇳🇵",
    accent: "ne-NP-female-13",
  },
  {
    code: "nl",
    name: "Dutch",
    native: "Nederlands",
    flag: "🇳🇱",
    accent: "nl-NL-female-14",
  },
  {
    code: "or",
    name: "Oriya",
    native: "ଓଡ଼ିଆ",
    flag: "🇮🇳",
    accent: "or-IN-female-1",
  },
  {
    code: "pa",
    name: "Panjabi / Punjabi",
    native: "ਪੰਜਾਬੀ / पंजाबी / پنجابي",
    flag: "🇮🇳",
    accent: "pa-IN-female-1",
  },
  {
    code: "pl",
    name: "Polish",
    native: "Polski",
    flag: "🇵🇱",
    accent: "pl-PL-female-14",
  },
  {
    code: "ps",
    name: "Pashto",
    native: "پښتو",
    rtl: true,
    flag: "🇦🇫",
    accent: "ps-AF-female-13",
  },
  {
    code: "pt",
    name: "Portuguese",
    native: "Português",
    flag: "🇧🇷",
    accent: "pt-BR-female-14",
  },
  {
    code: "ro",
    name: "Romanian",
    native: "Română",
    flag: "🇷🇴",
    accent: "ro-RO-female-14",
  },
  {
    code: "ru",
    name: "Russian",
    native: "Русский",
    flag: "🇷🇺",
    accent: "ru-RU-female-15",
  },
  {
    code: "si",
    name: "Sinhalese",
    native: "සිංහල",
    flag: "🇱🇰",
    accent: "si-LK-female-14",
  },
  {
    code: "sk",
    name: "Slovak",
    native: "Slovenčina",
    flag: "🇸🇰",
    accent: "sk-SK-female-14",
  },
  {
    code: "sl",
    name: "Slovenian",
    native: "Slovenščina",
    flag: "🇸🇮",
    accent: "sl-SI-female-14",
  },
  {
    code: "so",
    name: "Somalia",
    native: "Soomaaliga",
    flag: "🇸🇴",
    accent: "so-SO-female-14",
  },
  {
    code: "sq",
    name: "Albanian",
    native: "Shqip",
    flag: "🇦🇱",
    accent: "sq-AL-female-14",
  },
  {
    code: "sr",
    name: "Serbian",
    native: "Српски",
    flag: "🇷🇸",
    accent: "sr-RS-female-14",
  },
  {
    code: "su",
    name: "Sundanese",
    native: "Basa Sunda",
    flag: "🇮🇩",
    accent: "su-ID-female-14",
  },
  {
    code: "sv",
    name: "Swedish",
    native: "Svenska",
    flag: "🇸🇪",
    accent: "sv-SE-female-15",
  },
  {
    code: "sw",
    name: "Swahili",
    native: "Kiswahili",
    flag: "🇹🇿",
    accent: "sw-KE-female-14",
  },
  {
    code: "ta",
    name: "Tamil",
    native: "தமிழ்",
    flag: "🇮🇳",
    accent: "ta-IN-female-14",
  },
  {
    code: "te",
    name: "Telugu",
    native: "తెలుగు",
    flag: "🇮🇳",
    accent: "te-IN-female-14",
  },
  {
    code: "th",
    name: "Thai",
    native: "ไทย / Phasa Thai",
    flag: "🇹🇭",
    accent: "th-TH-female-15",
  },
  {
    code: "tr",
    name: "Turkish",
    native: "Türkçe",
    flag: "🇹🇷",
    accent: "tr-TR-female-15",
  },
  {
    code: "uk",
    name: "Ukrainian",
    native: "Українська",
    flag: "🇺🇦",
    accent: "uk-UA-female-14",
  },
  {
    code: "ur",
    name: "Urdu",
    native: "اردو",
    rtl: true,
    flag: "🇵🇰",
    accent: "ur-PK-female-14",
  },
  {
    code: "uz",
    name: "Uzbek",
    native: "Ўзбек",
    flag: "🇺🇿",
    accent: "uz-UZ-female-14",
  },
  {
    code: "vi",
    name: "Vietnamese",
    native: "Tiếng Việt",
    flag: "🇻🇳",
    accent: "vi-VN-female-14",
  },
  {
    code: "zh",
    name: "Chinese",
    native: "中文",
    flag: "🇨🇳",
    accent: "zh-CN-female-15",
  },
  {
    code: "zu",
    name: "Zulu",
    native: "isiZulu",
    flag: "🇿🇦",
    accent: "zu-ZA-female-17",
  },
];

export default languages;
